name: Brien McCrea
favicon: null
layout_spectrum: 0.5740289008244872
typography_spectrum: 0.5898802343290299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbe5e2'
    - '#d29c8b'
    - '#342625'
    - '#78676d'
    - '#973012'
  brandStrength: 0.3125
  lightness: 0.1285584440920502
  saturation: 0.5
  rhythmicContrast: 0.321355773601681
purpose: []
